# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adjuster',
            old_name='mobile',
            new_name='phone',
        ),
    ]
