# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170930_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjuster',
            name='lat',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='adjuster',
            name='lng',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='adjuster',
            name='photo',
            field=models.ImageField(blank=True, upload_to='adjusters'),
        ),
    ]
