# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_claim_damagedfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjuster',
            name='photo',
            field=models.ImageField(blank=True, default='static/dashboard/gfx/person-placeholder.png', upload_to='adjusters'),
        ),
    ]
