# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 16:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_auto_20171002_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjuster',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adjuster',
            name='lat',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='adjuster',
            name='lng',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True),
        ),
    ]
