# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-02 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20171002_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='addr_street_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='region',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='zip_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
