# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20171006_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='zip_code',
            new_name='postal_code',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='country',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='region',
        ),
    ]
