# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20171006_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='completed',
        ),
        migrations.AddField(
            model_name='claim',
            name='state',
            field=models.CharField(choices=[('assigned', 'assigned'), ('started', 'started'), ('completed', 'completed')], default=1, max_length=100),
        ),
    ]
