# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20171006_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimfield',
            old_name='_range',
            new_name='range',
        ),
    ]
