# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20171006_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimfield',
            name='crop_type',
        ),
        migrations.AddField(
            model_name='claimfield',
            name='type',
            field=models.CharField(blank=True, choices=[('cereals', 'Cereals'), ('oilseeds', 'Oilseeds'), ('pulses', 'Pulses')], max_length=50),
        ),
    ]
