# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20171006_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='assigned',
            new_name='assigned_adjuster',
        ),
    ]
