# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20171006_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimfield',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='state',
            field=models.CharField(choices=[('assigned', 'assigned'), ('started', 'started'), ('completed', 'completed')], default='started', max_length=100),
        ),
        migrations.AlterField(
            model_name='claimfield',
            name='type',
            field=models.CharField(choices=[('cereals', 'Cereals'), ('oilseeds', 'Oilseeds'), ('pulses', 'Pulses')], max_length=50),
        ),
    ]
