# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20171007_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='claimfield',
            name='loss',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
