# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20171010_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='name',
        ),
    ]
