# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_remove_claim_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjuster',
            name='push_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
