# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_adjuster_push_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimfield',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
