# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20171012_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimFieldPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='fields')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ClaimField')),
            ],
        ),
        migrations.AlterField(
            model_name='adjuster',
            name='lat',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adjuster',
            name='lng',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
