# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20171012_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimfieldphoto',
            name='field',
        ),
    ]
