# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_remove_claimfieldphoto_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimfieldphoto',
            name='field',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dashboard.ClaimField'),
            preserve_default=False,
        ),
    ]
