# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_claimfieldphoto_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimfieldphoto',
            name='field',
        ),
        migrations.AddField(
            model_name='claimfield',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='fields'),
        ),
        migrations.DeleteModel(
            name='ClaimFieldPhoto',
        ),
    ]
