# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-02 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20171012_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='assigned_adjuster',
        ),
        migrations.AddField(
            model_name='claim',
            name='adjusters',
            field=models.ManyToManyField(blank=True, to='dashboard.Adjuster'),
        ),
        migrations.AddField(
            model_name='claim',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='time_limit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
