# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-03 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_auto_20181102_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
