# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-07 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_auto_20181103_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
